export const AIKeywords = {
  "keywords": [
    // English
    "AI",
    "Artificial Intelligence",
    "Data Analytics",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Image Processing",
    "Natural Language Processing",
    "NLP",
    "Robotics",
    "Automation",
    "Big Data",
    "Neural Networks",
    "Predictive Analytics",
    "Cognitive Computing",
    "Speech Recognition",
    "Data Science",
    "Reinforcement Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Artificial Neural Networks",
    "Convolutional Neural Networks",
    "Generative Adversarial Networks",
    "Generative AI",
    "Generative Artificial Intelligence",
    "GANs",
    "AI Ethics",
    "AI Governance",
    "Explainable AI",
    "XAI",
    "AI Policy",
    "Smart Systems",
    "Intelligent Systems",
    "Decision Support Systems",
    "Expert Systems",
    "Pattern Recognition",
    "Fuzzy Logic",
    "Swarm Intelligence",
    "Bayesian Networks",
    "Knowledge Representation",
    "AI Research",
    "AI Development",
    "Computer Science",
    "Computer Software Engineering",
    "Computer Engineering Technology",
    "Digital Transformation",
    "Edge AI",
    "Cloud Computing",
    "Cloud AI",
    "AI in Healthcare",
    "AI in Education",
    "AI in Finance",
    "AI in Agriculture",
    "AI in Industry",
    "AI in Transportation",
    "AI in Energy",
    "AI Applications",
    "AI Frameworks",
    "AI Tools",
    "Data Mining",
    "Natural Language Understanding (NLU)",
    "Chatbots",
    "Autonomous Vehicles",
    "AI Regulations",
    "AI and Sustainability",
    "Human-Centric AI",
    "Bias in AI",
    "AI Risk Assessment",
    "Federated Learning",
    "Quantum Computing in AI",
    "AI Infrastructure",
    "AI Adoption",
    "AI Workshops",
    "AI Awareness",
    "AI Strategy",
    "AI Readiness",
    "AI in Cloud Computing",
    "Cloud AI Integration",
    "Edge Computing in AI",
    "Serverless Computing",
    "Multi-cloud Strategies",
    "Hybrid Cloud AI",
    "AI in DevOps",
    "AI in IoT",
    "AI-Powered Cloud Services",
    "AI and Blockchain",
    "AI for Cybersecurity",
    "AI in Privacy Protection",
    "Cloud-Native AI Solutions",
    "AI-Based Cloud Infrastructure",
    "AI for Digital Twins",
    "AI in Smart Cities",
    "AI for Disaster Management",
    "AI and 5G Networks",
    "AI-Driven Cloud Solutions",
    "AI in SaaS",
    "AI in PaaS",
    "AI in IaaS",
    "AI for Cloud Automation",
    "AI for Data Security",
    "AI for Cloud Migration",
    "AI Cloud Optimization",
    "Quantum Cloud Computing",
    "AI Cloud Analytics",
    "AI Data Lakes",
    "Cloud-Based Machine Learning",
    "AI in Cloud Security",
    "AI-Optimized Data Centers",
    "AI Infrastructure as a Service",
    "AI for Cloud-Native Applications",
    "Edge AI in Cloud",
    "Distributed Cloud AI",
    "AI and Cloud Platforms",
    "Cloud Infrastructure Automation",
    "AI-Driven Cloud Security",
    "AI Cloud Monitoring",
    "AI Cloud Analytics Platforms",
    "Cloud Data Science",
    "AI and Cloud DevOps",
    "AI Cloud-Based Models",
    "AI Cloud Technologies",
    "AI Cloud Innovation",
    "AI Cloud Management",
    "AI Cloud Solutions",
    "AI in Cloud Architecture",
    "AI Cloud Integration Tools",
    "AI-Powered Cloud Technologies",
    "Cloud AI for Business Transformation",
    "AI Cloud Adoption Frameworks",
    "AI Cloud Deployment",
    "AI in Public Cloud",
    "AI in Hybrid Cloud Environments",
    "Cloud-Native Digital Transformation",
    "AI-Driven Cloud Computing Solutions",
    "AI Cloud Solutions for Retail",
    "AI Cloud for Virtual Assistants",
    "Cloud AI for Customer Experience",
    "AI Cloud Solutions for Marketing",
    "AI Cloud Platforms for Data Science",
    "AI Cloud-Integrated Development Tools",
    "AI Cloud in SaaS Solutions",
    "Cloud-Based AI Model Training",
    "AI Cloud Data Management",
    "AI Cloud Optimization Strategies",
    "AI Cloud Monitoring Solutions",
    "AI-Optimized Cloud Workloads",
    "AI Cloud for Supply Chain Optimization",
    "AI Cloud for Smart Manufacturing",
    "Cloud AI for Real-Time Data",
    "AI for Cloud-Native Digital Transformation",
    "Cloud AI Innovations",
    "AI-Powered Cloud Computing Solutions",
    "Cloud AI Strategy",
    "AI Cloud for IT Operations",
    "AI for Cloud-Based Systems",
    "AI-Cloud Synergy",
    
    // Arabic
    "الذكاء الاصطناعي",
    "تحليل البيانات",
    "تعلم الآلة",
    "التعلم العميق",
    "رؤية الحاسوب",
    "معالجة الصور",
    "معالجة اللغة الطبيعية",
    "الروبوتات",
    "الأتمتة",
    "البيانات الضخمة",
    "الشبكات العصبية",
    "التحليلات التنبؤية",
    "الحوسبة الإدراكية",
    "التعرف على الكلام",
    "علم البيانات",
    "التعلم التعزيزي",
    "التعلم تحت الإشراف",
    "التعلم غير الخاضع للإشراف",
    "التعلم شبه الخاضع للإشراف",
    "الشبكات العصبية الاصطناعية",
    "الشبكات العصبية الالتفافية",
    "الشبكات التنافسية التوليدية",
    "الذكاء الاصطناعي التوليدي",
    "أخلاقيات الذكاء الاصطناعي",
    "حوكمة الذكاء الاصطناعي",
    "الذكاء الاصطناعي القابل للتفسير",
    "سياسة الذكاء الاصطناعي",
    "الأنظمة الذكية",
    "أنظمة دعم القرار",
    "أنظمة الخبراء",
    "التعرف على الأنماط",
    "المنطق الضبابي",
    "الذكاء السربي",
    "الشبكات البايزية",
    "تمثيل المعرفة",
    "أبحاث الذكاء الاصطناعي",
    "تطوير الذكاء الاصطناعي",
    "علوم الحاسوب",
    "هندسة برمجيات الحاسوب",
    "تقنية هندسة الحاسوب",
    "التحول الرقمي",
    "ذكاء الحافة",
    "الحوسبة السحابية",
    "الذكاء الاصطناعي في الصحة",
    "الذكاء الاصطناعي في التعليم",
    "الذكاء الاصطناعي في المالية",
    "الذكاء الاصطناعي في الزراعة",
    "الذكاء الاصطناعي في الصناعة",
    "الذكاء الاصطناعي في النقل",
    "الذكاء الاصطناعي في الطاقة",
    "تطبيقات الذكاء الاصطناعي",
    "أطر عمل الذكاء الاصطناعي",
    "أدوات الذكاء الاصطناعي",
    "تنقيب البيانات",
    "فهم اللغة الطبيعية",
    "الدردشة الآلية",
    "المركبات ذاتية القيادة",
    "تنظيم الذكاء الاصطناعي",
    "الذكاء الاصطناعي والاستدامة",
    "الذكاء الاصطناعي المتمحور حول الإنسان",
    "التحيز في الذكاء الاصطناعي",
    "تقييم مخاطر الذكاء الاصطناعي",
    "التعلم الموحد",
    "الحوسبة الكمية في الذكاء الاصطناعي",
    "بنية الذكاء الاصطناعي التحتية",
    "تبني الذكاء الاصطناعي",
    "ورش عمل الذكاء الاصطناعي",
    "رفع الوعي بالذكاء الاصطناعي",
    "استراتيجية الذكاء الاصطناعي",
    "الجاهزية للذكاء الاصطناعي",
    "الذكاء الاصطناعي في الحوسبة السحابية",
    "تكامل الذكاء الاصطناعي في السحابة",
    "الحوسبة السحابية في الذكاء الاصطناعي",
    "الذكاء الاصطناعي في الأمن السيبراني",
    "الذكاء الاصطناعي في البيانات الكبيرة",
    "الذكاء الاصطناعي في تحسين العمليات",
    "الذكاء الاصطناعي في تحليل البيانات",
    "الذكاء الاصطناعي في التجارة الإلكترونية",
    "الحوسبة السحابية لتدريب النماذج الذكية",
    "الحوسبة السحابية في إنترنت الأشياء",
    "الذكاء الاصطناعي في إدارة الموارد",
    "الحوسبة السحابية في الأنظمة الذكية",
    "الذكاء الاصطناعي في إدارة البيانات",
    "الحوسبة السحابية للأمن والحماية",
    "الذكاء الاصطناعي في المدن الذكية",
    "الذكاء الاصطناعي في الزراعة الذكية",
    "الذكاء الاصطناعي في تحسين الطاقة",
    "الذكاء الاصطناعي في الرعاية الصحية",
    "الذكاء الاصطناعي في التصنيع الذكي",
    "الذكاء الاصطناعي في حلول التعليم",
    "الذكاء الاصطناعي في التحول الرقمي",
    "الذكاء الاصطناعي عبر المنصات السحابية",
    "الذكاء الاصطناعي في التحليل التنبؤي",
    "الذكاء الاصطناعي في الواقع المعزز",
    "الحوسبة السحابية في تحليلات البيانات",
    "الذكاء الاصطناعي في التصوير الطبي",
    "الذكاء الاصطناعي في النقل الذكي",
    "الذكاء الاصطناعي في الخدمات المالية",
    "الذكاء الاصطناعي في التعليم عبر السحابة",
    "الحوسبة السحابية في الذكاء الاصطناعي متعدد السحب",
    "الذكاء الاصطناعي عبر الحلول السحابية المتقدمة"
  ]
};
