export const AIKeywords = {
  "keywords": [
    "AI ",
    "Artificial Intelligence",
    "Data Analytics",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Image Processing",
    "Natural Language Processing",
    "NLP",
    "Robotics",
    "Automation",
    "Big Data",
    "Neural Networks",
    "Predictive Analytics",
    "Cognitive Computing",
    "Speech Recognition",
    "Data Science",
    "Reinforcement Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Artificial Neural Networks",
    "Convolutional Neural Networks",
    "Generative Adversarial Networks",
    "Generative AI",
    "Generative Artificial Intelligence",
    "GANs",
    "AI Ethics",
    "AI Governance",
    "Explainable AI",
    "XAI",
    "AI Policy",
    "Smart Systems",
    "Intelligent Systems",
    "Decision Support Systems",
    "Expert Systems",
    "Pattern Recognition",
    "Fuzzy Logic",
    "Swarm Intelligence",
    "Bayesian Networks",
    "Knowledge Representation",
    "AI Research",
    "AI Development",
    "Computer Science",
    "Computer Software Engineering",
    "Computer Engineering Technology"
  ]
}
