# Generated by Django 5.0.4 on 2024-07-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=255)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('company_type', models.CharField(blank=True, max_length=255)),
                ('follower_count', models.IntegerField(default=0)),
                ('company_twitter_username', models.CharField(blank=True, max_length=255)),
                ('company_twitter_followers', models.IntegerField(default=0)),
                ('company_twitter_id', models.CharField(blank=True, max_length=255)),
                ('company_twitter_created_at', models.DateTimeField(blank=True, null=True)),
                ('company_twitter_description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTweetSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('proficiency', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('full_text', models.TextField(blank=True)),
                ('blog_url', models.URLField(blank=True, unique=True)),
                ('blog_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_text', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('job_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_text', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyNewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('news_url', models.URLField(blank=True, max_length=1000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_text', models.TextField(blank=True)),
                ('news_date', models.DateField(blank=True, null=True)),
                ('is_event', models.BooleanField(default=False)),
                ('is_news', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('added_at', models.DateTimeField()),
                ('full_text', models.TextField()),
                ('favorite_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('conversation_id', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=10)),
                ('possibly_sensitive', models.BooleanField(default=False)),
                ('quoted_status_id', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
                ('symbols', models.ManyToManyField(related_name='tweet', to='talent.companytweetsymbol')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('geographic_area', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('line1', models.CharField(blank=True, max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_headquarter', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('public_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('email_required', models.BooleanField(default=False)),
                ('open_connection', models.BooleanField(default=False)),
                ('profile_pic', models.URLField(blank=True)),
                ('current_company_name', models.CharField(blank=True, max_length=255)),
                ('current_company_link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_data_json', models.JSONField(blank=True, null=True)),
                ('current_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.company')),
                ('languages', models.ManyToManyField(to='talent.language')),
                ('skills', models.ManyToManyField(to='talent.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAndCertifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HonorAndAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_link', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_link', models.CharField(blank=True, max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('schoolName', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAndAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_link', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_text', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.company')),
            ],
            options={
                'unique_together': {('title', 'company')},
            },
        ),
    ]
