# Generated by Django 5.0.4 on 2024-07-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_alter_location_postal_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyTweet',
            new_name='Tweet',
        ),
        migrations.RenameModel(
            old_name='CompanyTweetSymbol',
            new_name='TweetSymbol',
        ),
    ]
