# Generated by Django 5.0.4 on 2024-07-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_rename_companytweet_tweet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsymbol',
            name='times_mentioned',
            field=models.IntegerField(default=0),
        ),
    ]
