# Generated by Django 5.0.4 on 2024-07-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_tweetsymbol_times_mentioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='language',
            name='times_mentioned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skills',
            name='times_mentioned',
            field=models.IntegerField(default=0),
        ),
    ]
