# Generated by Django 5.0.4 on 2024-07-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_remove_language_proficiency_language_times_mentioned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.employeeurls'),
        ),
    ]
