# Generated by Django 5.0.4 on 2024-07-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_employeeurls_userprofile_employee_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeUrls',
            new_name='EmployeeUrl',
        ),
    ]
