# Generated by Django 5.0.4 on 2024-07-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_rename_employeeurls_employeeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='unique_username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
