# Generated by Django 5.0.4 on 2024-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_company_unique_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='unique_username',
        ),
    ]
