# Generated by Django 5.0.4 on 2024-07-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_remove_company_unique_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerandawards',
            name='end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerandawards',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
