# Generated by Django 5.0.4 on 2024-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0010_alter_education_end_alter_education_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseandcertifications',
            name='end',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='licenseandcertifications',
            name='start',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerandawards',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerandawards',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
