# Generated by Django 5.0.4 on 2024-07-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0013_companyproducts_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='company_twitter_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
