# Generated by Django 5.0.4 on 2024-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_tweet_company_twitter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
