# Generated by Django 5.0.4 on 2024-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0016_alter_companyproducts_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='times_mentioned',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skills',
            name='times_mentioned',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tweetsymbol',
            name='times_mentioned',
            field=models.IntegerField(default=1),
        ),
    ]
