# Generated by Django 5.0.6 on 2024-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0020_alter_company_linkedin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyblog',
            name='blog_url',
            field=models.URLField(blank=True, max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companyblog',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='job_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='companynewsandevents',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='companynewsandevents',
            name='news_url',
            field=models.URLField(blank=True, max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='companyproducts',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='companyproducts',
            name='product_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='employeeurl',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
