# Generated by Django 5.0.6 on 2024-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0021_alter_companyblog_blog_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseandcertifications',
            name='end',
            field=models.DateField(blank=True, max_length=2000, null=True),
        ),
    ]
